### PR TITLE
Added dbus type double to ldbus.types and ldbus.basic_types

### PR DESCRIPTION
**Pull request by dodo**
kind'a self explanatory :)

And could you please update https://rocks.moonscript.org/modules/daurnimator/ldbus ?

Thank you very much.

### CODE REVIEW

**Comment by daurnimator** [comment]
I've got some large changes half completed for ldbus, just need a free weekend to work on them. I'll merge this in then.

**Comment by daurnimator** [comment]
looking at your patch; please follow existing indentation (i.e. use tabs, not spaces).
Also, please add the new type to the README

**Comment by dodo** [comment]
awesome!

**Comment by daurnimator** [comment]
Looks good. merging without testing.

**Comment by daurnimator** [comment]
btw, what did you need this for? it's just a single character 'd' :P

**Comment by dodo** [comment]
https://github.com/dodo/lua-dbus/blob/scm-0/awesome/dbus.lua#L160 :)

Actually i don't _need_ it, but i noticed it was missing, so i added it.

**Pull request closed without merging**
